src/Entity/Stage.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StageRepository")
 */
class Stage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $entreprise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="integer")
     */
    private $code_postal;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_created;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $domaine;

    /**
     * @ORM\Column(type="datetime")
     */
    private $periode;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $niveau;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="stages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $entreprise_s;

    public function getId()
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(string $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getDomaine(): ?string
    {
        return $this->domaine;
    }

    public function setDomaine(string $domaine): self
    {
        $this->domaine = $domaine;

        return $this;
    }

    public function getPeriode(): ?\DateTimeInterface
    {
        return $this->periode;
    }

    public function setPeriode(\DateTimeInterface $periode): self
    {
        $this->periode = $periode;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getNiveau(): ?string
    {
        return $this->niveau;
    }

    public function setNiveau(string $niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getEntrepriseS(): ?Entreprise
    {
        return $this->entreprise_s;
    }

    public function setEntrepriseS(?Entreprise $entreprise_s): self
    {
        $this->entreprise_s = $entreprise_s;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;
use App\Repository\StageRepository;
use App\Repository\EntrepriseRepository;
use App\Entity\Stage;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Entreprise;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="default")
     */
    public function index(StageRepository $stageRepository, EntrepriseRepository $entrepriseRepository)
    {
        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
            'stages' => $stageRepository->findAll(),
            'entreprises' => $entrepriseRepository->findAll(),
        ]);
    }


}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ado Stage!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="jumbotron text-center">
    <h1 class="display-3">Salut Ado Stage</h1>
    <p class="lead">Tu cherches un stage</p>
    <p class="lead">
        <a class="btn btn-warning btn-lg text-dark" href="#" role="button">Voir plus</a>
    </p>
</div>
<h1 class="text-center">Les stages</h1>
<div class="container-fluid">
    {% for entreprise in entreprises %}
    <div class="row">
        <div class="col-md-3">
            <div class="card border-warning mb-3" style="max-width: 20rem;">
                <div class="card-header">{{ entreprise.title}}</div>
                <div class="card-body">
                    <h4 class="card-title">{{ entreprise.title }}</h4>
                    <p class="card-text">{{ entreprise.adresse }}</p>


                </div>
            </div>
        </div>
    </div>
    {% else %}
        <tr>
            <td colspan="14">no records found</td>
        </tr>
    {% endfor %}
</div>

    {% for stage in stages %}
        <tr>
            <td>{{ stage.id }}</td>
            <td></td>
            <td>{{ stage.entreprise }}</td>
            <td>{{ stage.description }}</td>
            <td>{{ stage.email }}</td>
            <td>{{ stage.ville }}</td>
            <td>{{ stage.adresse }}</td>
            <td>{{ stage.codePostal }}</td>
            <td>{{ stage.dateCreated ? stage.dateCreated|date('d/m/Y') : '' }}</td>
            <td>{{ stage.domaine }}</td>
            <td>{{ stage.periode ? stage.periode|date('d/m/Y') : '' }}</td>
            <td>{{ stage.duree }}</td>
            <td>{{ stage.niveau }}</td>
        </tr>
    {% else %}
        <tr>
            <td colspan="14">no records found</td>
        </tr>
    {% endfor %}


{% endblock %}